### PR TITLE
blank notepad not needed

### PR DESCRIPTION
**Pull request by xyzze**

### CODE REVIEW

**Comment by amitxv** [comment]
Installation should fail if it's removed due to a mismatch with the inf configuration, do you not get any errors?

**Comment by Vojtazz** [comment]
no errors at all, tested on two cards, with the latest driver.

**Comment by amitxv** [comment]
I'll try this on my AMD gpu when i'm free as i still have doubts, will keep this PR open meanwhile

**Comment by Vojtazz** [comment]
Sure, however it was tested on RX6600XT and 6900XT.

**Comment by xyzze** [comment]
I am closing it as i moved to NVidia currently

**Pull request closed without merging**
