### PR TITLE
Disable more Telemetry for Firefox.cfg

### PR DESCRIPTION
**Pull request by 99N9ne99**

### CODE REVIEW

**Comment by amitxv** [comment]
Both of these prefs are included in arkenfox's user.js so including it in firefox.cfg is not required. My intention is to slightly declutter the home page on a fresh install and include the basic prefs such as enabling compact UI etc.

One may argue that disabling telemetry is included in the "include basics prefs" criteria mentioned above but where will it stop? It is easy to get carried away with adding many more after that and for that reason, i'll leave it to user.js from arkenfox to configure prefs not visible to the user.

**Comment by amitxv** [comment]
I have been meaning to review the prefs included in firefox.cfg, there are a few which are overridden by other prefs such as the child settings under the parent setting in the image below as an example which is why there are many included.

image

**Comment by 99N9ne99** [comment]
I understand, what about the new list page tab and firefox view both clutter the ui imo and are not handled by arkenfox?

**Comment by amitxv** [comment]
Do you mind sending a picture of the UI components you mentioned above?

**Comment by amitxv** [comment]
Unrelated, I also noticed the following are handled by arkenfox so they *could* be removed.

```
defaultPref("app.shield.optoutstudies.enabled", false);
defaultPref("datareporting.healthreport.uploadEnabled", false);
defaultPref("dom.security.https_only_mode", true);
```

**Comment by 99N9ne99** [comment]
on the top right its the firefox view ("browser.tabs.firefox-view", false)
Screenshot_20221117_081128
and on the right its the tab list ("browser.tabs.tabmanager.enabled", false)
Screenshot_20221117_081156

**Comment by 99N9ne99** [comment]
> 

no i understand it

**Pull request closed without merging**
