### PR TITLE
Opt out of .NET & PowerShell Telemetry

### PR DESCRIPTION
**Pull request by esruv**
Added commands to opt out of .NET & PowerShell Telemetry.

### CODE REVIEW

**Comment by amitxv** [comment]
DOTNET_CLI_TELEMETRY_OPTOUT is not relevant to a standard windows install as it is related to SDK telemetry

https://learn.microsoft.com/en-us/dotnet/core/tools/telemetry

POWERSHELL_TELEMETRY_OPTOUT could be set in registry as it is not something that should be optional to the end user. Any info on the minimum supported client? If not, I can assume it exists on windows 7+

**Comment by esruv** [comment]
PowerShell one exists on 7+ pretty sure

As for the .NET Telemetry I believe its in the Core aswell so I'd assume its in the Desktop Runtime aswell could be a very precautionary thing not sure. 

Old post from 2016 about them considering .NET Runtime telemetry aswell: https://github.com/dotnet/sdk/issues/6145#issuecomment-220082687

More info on .NET Telemetry:
https://docs.contrastsecurity.com/en/-net-telemetry-100740.html

**Comment by amitxv** [comment]
The second page suggests a different variable, CONTRAST_DOTNET_TELEMETRY_OPTOUT

I'm unsure if this applies to the runtime itself

**Comment by esruv** [comment]
Yeah not sure either I'm probably gonna look through this at some point probably plus seems useful:
https://github.com/dotnet/sdk/tree/main/src/Cli/dotnet/Telemetry

Considering in newer versions of Windows .NET Framework 4.8 is implemented already so I add the ones I listed. also the CONTRAST_DOTNET_TELEMETRY_OPTOUT you sent might be a sub-category of the telemetry (more or less guessing) and DOTNET_CLI_TELEMETRY_OPTOUT is global? (My idea of it)

**Comment by amitxv** [comment]
CONTRAST_DOTNET_TELEMETRY_OPTOUT does not show up at all in that repository DOTNET_CLI_TELEMETRY_OPTOUT is there but not as frequent as TELEMETRY_OPTOUT

https://github.com/dotnet/sdk/blob/cb5a24da813307788d985e92fd85ac563295b9a1/src/Cli/dotnet/Telemetry/Telemetry.cs#L51

**Comment by esruv** [comment]
As a precaution I would probably add these options, doesn't seem to have any negatives. (prob better to put in reg file) But I understand not wanting to add redundant/non-relevant things sucks that Microsoft doesn't have easier/more accessible documentation for Telemetry.

I'll probably do some more digging on it tomorrow.

**Pull request closed without merging**
