### PR TITLE
Update NSudo to the latest preview version, to:

### PR DESCRIPTION
**Pull request by Vojtazz**
prevent it from not creating process (-2147024891)

### CODE REVIEW

**Comment by amitxv** [comment]
When does that error occur? Steps in reproducing the problem would be helpful

**Comment by Vojtazz** [comment]
When trying to open process as admin e.g. cmd exe, same problem occured on custom isos where some things were stripped.

**Comment by amitxv** [comment]
My project is not a custom iso and it does not involve the use of tools such as NTLite which removes far more dependencies than the methods i use. It works fine for me 
image

**Comment by Vojtazz** [comment]
Then i am closing.

**Pull request closed without merging**
