### PR TITLE
improvents and final thoughts fix

### PR DESCRIPTION
**Pull request by Vojtazz**

### CODE REVIEW

**Comment by amitxv** [comment]
The missing punctuation mark is intentional and the *Final Thoughts & Tips* link was amended in #1

**Comment by Vojtazz** [comment]
i meant thoughts in: "
- In ``Defragment and Optimize Drives``, disable ``Run on a schedule``. More details on doing maintenance tasks ourself in [Final Thoughts & Tips]"

**Comment by Vojtazz** [comment]
link is wrong

**Comment by amitxv** [comment]
It is working perfectly fine

**Pull request merged**
