### PR TITLE
Formatting, more information, improvements

### PR DESCRIPTION
**Pull request by Vojtazz**
- Formatting, beter visibility
- Fix typos
- added info on start menu
- added standby states to the powerplan options
- extended 7-Zip section
- remove not needed mpc-hc link

### CODE REVIEW

**Comment by nicklvh** [comment]
WordPad is spelt WordPad not Wordpad btw

**Comment by Vojtazz** [comment]
> WordPad

right, thanks

**Comment by nicklvh** [comment]
thanks 👍
everything else looks good

**Comment by Vojtazz** [comment]
pushed one more commit

**Comment by amitxv** [comment]
Sorry but there are too many unnecessary changes, will cherry-pick changes manually

**Comment by Vojtazz** [comment]
thanks

**Pull request closed without merging**
